// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQA-DS9qy4Xp8X4fOv4mjUooGH14ftf3Y',
    appId: '1:975207760592:web:430e09cfd9894a21d9d4d5',
    messagingSenderId: '975207760592',
    projectId: 'app-fire-a2a49',
    authDomain: 'app-fire-a2a49.firebaseapp.com',
    databaseURL: 'https://app-fire-a2a49-default-rtdb.firebaseio.com',
    storageBucket: 'app-fire-a2a49.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXUaBMckPvEr9Mgfb7RRQjaI7wECzyiV0',
    appId: '1:975207760592:android:8ad36070bdb6f207d9d4d5',
    messagingSenderId: '975207760592',
    projectId: 'app-fire-a2a49',
    databaseURL: 'https://app-fire-a2a49-default-rtdb.firebaseio.com',
    storageBucket: 'app-fire-a2a49.firebasestorage.app',
  );
}
